name = "nixpkgs-watch"
main = "src/index.js"
compatibility_date = "2026-08-29"

[[routes]]
pattern = "nixpkgs-watch.nolight.dev"
custom_domain = true

[triggers]
crons = ["* * * * *"]

[vars]
REPO = "nolight132/nixpkgs-ci"
REF = "main"
FLOOR_MINUTES = "15"

[[kv_namespaces]]
binding = "STATE"
id = "16e61c85f6904d2ca2f53f035dc52415"
